config/routes.rb
Rails.application.routes.draw do
  root 'relationship_officers#new'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'relationship_officers#new'
  post '/signup', to: 'relationship_officers#create'
  get '/profile', to: 'relationship_officers#show'
  get '/addclient', to: 'clients#new'
  post '/addclient', to: 'clients#create'
  get '/viewclient', to: 'clients#show'
  get '/search', to: 'clients#search'
  patch '/updatedetails', to: 'clients#update'
  post 'clientpaid', to: 'clients#client_payment'
  resources :relationship_officers
  resources :clients 
  resources :short_loans
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @current_user = current_user
    @client_details = @current_user.client_details
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div id="modal-parent">
    <div id = "myModal" class="payment-modal">
        
    </div>
</div>


<main class="home">
    <section class="container">
        <div class="welcome-section">
            <div class="greeting">
                <p>Welcome,<br><span class="user-name"><%= current_user.name%></span></p>
            </div>
            <div>
                <button class="add-client-btn btn"><%= link_to "Add client", addclient_path%></button>
            </div>
        </div>
    </section>
     <div class="container">
        <p>Your stats for today</p>
    </div>
    <section class="stats container">
        <div class="user-stats">
        <div class="total-dues stats-box">
            <div class="stat">
                <h1><%= current_user.total_dues%></h1>
            </div>
            <div class="sec-text">
                <p>Total Dues</p>
            </div>
        </div>
        <div class="client-count stats-box">
            <div class="stat">
                <h1><%= current_user.client_count%></h1>
            </div>
            <div class="sec-text">
                <p>Clients Due</p>
            </div>
        </div>
        <div class="collection-rate stats-box">
            <div class="stat">
                <h1 id="cr"><%= current_user.collection_rate%> %</h1>
            </div>
            <div class="sec-text">
                <p>Collection Rate</p>
            </div>
        </div>
        </div>
    </section>

    <section class="clients-due container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <p>Name</p>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <p>Phone No</p>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <p>Amount Due</p>
            </div>
        </div>
        <div>
            <%= render partial: "clients/client", collection: @client_details %>
        </div>
    </section>
</main>