config/routes.rb
Rails.application.routes.draw do
  root 'relationship_officers#new'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'relationship_officers#new'
  post '/signup', to: 'relationship_officers#create'
  get '/profile', to: 'relationship_officers#show'
  get '/addclient', to: 'clients#new'
  post '/addclient', to: 'clients#create'
  get '/viewclient', to: 'clients#show'
  get '/search', to: 'clients#search'
  patch '/updatedetails', to: 'clients#update'
  post 'clientpaid', to: 'clients#client_payment'
  resources :relationship_officers
  resources :clients 
  resources :short_loans
end

app/views/shared/_client_personal_info.html.erb
<section class="container" id="personal-information">
    <div class="inner-wrapper">
        <div class="personal-info">
            <h3>Personal Information</h3>
            <small>Edit client's personal details</small>
            <%= form_for client ,remote: true,class: "client-page-forms", id: "edit-client" do |form| %>
                <div>
                    <%= form.label :name , "First name", class: "client-label"%>
                    <%= form.text_field :name , class: "client-input"%>
                </div>
                <div>
                    <%= form.label :name , "Last Name", class: "client-label"%>
                    <%= form.text_field :name , class: "client-input"%> 
                </div>
                <div>
                    <%= form.label :phone_no , "Phone Number", class: "client-label"%>
                    <%= form.text_field :phone_no, class: "client-input" %> 
                </div>
                 <%= form.submit "Save Changes", class: "client-btn btn"%>
            <% end %>
           
        </div>
        <div class="create-new-loan">
            <h3>Add new loan</h3>
            <%= form_with model: ShortLoan.new ,local: true ,class: "client-page-forms" do |form| %>
                <%= form.hidden_field :relationship_officer_id , value: current_user.id %>
                <%= form.hidden_field :client_id , value: client.id%>

                <div>
                    <%= form.label :loan_amount , "Loan Amount", class: "client-label"%>
                    <%= form.text_field :loan_amount, class: "client-input"%>
                </div>
                <div>
                    <%= form.label :loan_duration , "Loan Duration", class: "client-label"%>
                    <%= form.select :loan_duration, [5,7,10], class: "client-input" %> 
                </div>
                <div>
                    <%= form.label :instalment_amount , "Instalment Amount", class: "client-label"%>
                    <%= form.text_field :instalment_amount, class: "client-input" %> 
                </div>
                <div>
                    <%= form.label :due_date, "Due Date", class: "client-label"%>
                    <i class="fa fa-calendar"></i>
                    <%= form.text_field :due_date,class: "date client-input"%>
                            
                </div>
                 <%= form.submit "Add", class: "client-btn btn"%>
            <% end %>
        </div>
    </div>
</section>

app/views/shared/_error_messages.html.erb
<% if @ro.errors.any? %>
    <div id="error_explanation", class="alert alert-danger">
        <ul>
            <% @ro.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="top-navbar container">
    <div class= "main-navbar">
        <% if logged_in?%>
         <%= link_to "LOGO", home_path, class: "navbar-brand"%> 
            <div class= "search-form">
                <div class="mobile-home">
                    <a href="/home"><i class="fa fa-home"></i></a>
                </div>
                <%= form_with url: search_path, method: :get, local: true, id: "search" do |form| %>
                    <div class="input">
                        <%= form.text_field :phone_no, placeholder: 'Enter client number'%>
                        <span class="input-group-search"><i class="fa fa-search"></i></span>
                    </div>
                <% end %>
                <%= image_tag("menu.svg", alt: "open navigation", class: "mobile-cta", id: "menu")%>
            </div>
            <div id="mobile-nav" class="mobile-menu">
                <div class="navigation-links">
                    <%= image_tag("exit.svg", alt: "close navigation", class: "mobile-menu-exit", id: "close-menu")%>
                    <ul>
                        <li><%= link_to "Home", home_path %></li>
                        <li><%= link_to "Profile", profile_path %></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li><%= link_to "Sign Out", logout_path, method: "delete"%></li>
                    </ul>
                </div>
             </div>
        <% else %>
            <div class="container">
            <div class="nav-sign">
                <div class="nav-sign-up">
                    <p class="navbar-brand-signup-page"> LOGO </p>
                    <div>
                        <%= image_tag("menu.svg", alt: "open navigation", class: "mobile-cta", id: "menu-sign-up")%>
                    </div>
                </div> 
                <div id="mobile-nav-signup" class="mobile-menu">
                    <div class="navigation-links">
                        <%= image_tag("exit.svg", alt: "close navigation", class: "mobile-menu-exit", id: "close-menu-signup")%>
                        <ul>
                            <li><%= link_to "About", "#"%></li>
                            <li><%= link_to "Help", "#"%></li>
                            <li><%= link_to "Sign In", login_path%></li>
                        </ul>
                    </div>
                </div> 
            </div> 
            </div>
           
        <% end %>
    </div>
</nav>

app/views/shared/_loan_info.html.erb
<main class="container" id="loan-info">
    <div class="inner-wrapper">
    
        <div class="loan-schedule">
            <h3>Loan Schedule</h3>
            <table>
                <tr>
                    <th>Instalment</th>
                    <th>Instalment Dates</th>
                </tr>
                <%@short_loan.loan_schedule.each_with_index do |element, idx| %>
                    <tr>
                        <td><%= idx + 1 %></td>
                        <td><%= @client.format_date(element.first) %></td> 
                    </tr>

                <% end %>
            </table>
        </div>
        <div class="other-loan-info">
            <h3>Loan Information</h3>
            <table>
                <tr>
                    <td>Initial Loan Balance</td>
                    <td><%=@short_loan.initial_balance %></td>
                </tr>
                <tr>
                    <td>Outstanding Loan Balance</td>
                    <td><%= @short_loan.outstanding_loan_balance%></td>
                </tr>
                <tr>
                    <td>Instalment Amount</td>
                    <td> <%= @short_loan.instalment_amount%></td>
                </tr>
                <tr>
                    <td>Loan Duration</td>
                    <td><%= @short_loan.loan_duration%></td>
                </tr>
            </table>
        </div>
    </div>
</main>