config/routes.rb
Rails.application.routes.draw do
  root 'relationship_officers#new'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'relationship_officers#new'
  post '/signup', to: 'relationship_officers#create'
  get '/profile', to: 'relationship_officers#show'
  get '/addclient', to: 'clients#new'
  post '/addclient', to: 'clients#create'
  get '/viewclient', to: 'clients#show'
  get '/search', to: 'clients#search'
  patch '/updatedetails', to: 'clients#update'
  post 'clientpaid', to: 'clients#client_payment'
  resources :relationship_officers
  resources :clients 
  resources :short_loans
end

app/models/client.rb
class Client < ApplicationRecord
    before_save {self.status = 'active'}
    validates :name, presence: true, length: {minimum: 6, maximum: 50}
    validates :phone_no, presence: true, length: {is: 10}, uniqueness: true
    validate :valid_phone  #fix using regex
    validates :relationship_officer_id, presence: true

    belongs_to :relationship_officer
    has_many :short_loans, inverse_of: :client
    accepts_nested_attributes_for :short_loans

    def format_date(date)
        date.split(" ").first
    end

    def self.update_client_details(update_params)
        client = Client.find(update_params[:id])
        client_details = update_params[:client]
        client_details.each do |key, value|
            column = key
            case column

            when 'phone_no'
                client.update_columns(phone_no: value)

            when 'name'
                client.update_columns(name: value)
            end
        end
     end

     def initial_loan_balance
        self.installment_amount * self.loan_duration
     end

     



    private

     def valid_phone
         errors.add(:phone_no, "Invalid format,number should start with zero") if phone_no.split("").first != "0"
     end

    
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController


    def new
        @client = Client.new
        @client.short_loans.build
    end

    def create
        
        @client = current_user.clients.build(client_params)
        Metric.create_metric(client_params[:short_loans_attributes][:"0"])
        if @client.save
            flash[:success] = "Created"
            redirect_to home_path
        else
            render 'new'
        end
    end

    def search
        @client = current_user.search(params[:phone_no])
       
        if @client.nil?
            redirect_to request.referrer, notice: "Client not found"
        else
            @short_loan = @client.short_loans.find(@client.id)
            render 'show'
        end

    end
    
    def show

    end

    def update
        Client.update_client_details(params)
        respond_to do |format|
            @client = Client.find(params[:id])
            format.js
        end
    end

    
    
    private

     def client_params
        params.require(:client).permit(:name,:phone_no,short_loans_attributes:[:relationship_officer_id,:loan_amount,:instalment_amount,:loan_duration,:due_date])
     end

end

app/helpers/clients_helper.rb
module ClientsHelper
    
end

app/views/clients/_client.html.erb
<div class="client row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <p><%= client[:name] %></p>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <p><%= client[:phone_no] %></p>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
       <p><%= client[:instalment]%></p>
       <div class="paid-checkbox">
            <label for="paid">Paid</label>
            <input type="checkbox" name="paid" id="paid" class= "pay" data-remote="true" data-url="/short_loans/<%= client[:loan_id]%>/edit" >
        </div>
    </div> 
</div>

app/views/clients/_modal.html.erb
  <div class="modal-content">
    <span class="close-modal">&times;</span>
    <p class="title">Client payment status</p>
    <%= form_with url: clientpaid_path do |form| %>
        <div class="payment-status">
            <div>
                <%= form.label "Full payment" %>
                <%= form.check_box :full_payment %>
            </div>
            <div>
                <p>For partial payment, enter amount paid</p>
                <%= form.text_field :amount, placeholder: 'Kshs', id: 'partial-payment'%>
            </div>
                <%= form.submit "Send", class: "modal-btn"%>
        </div>
    <% end %>
    
  </div>

app/views/clients/new.html.erb
<div class="container">
    <div class="client-form container">
        <h3>Create new client</h3>
        <%= form_for(@client) do |f| %>
        <div class="form-client-add-page">
            <div class="right-section"> 
                <div class="add-client-form">
                    <div>
                        <%= f.label :name, "Client Name", class: "client-label"%>
                        <%= f.text_field :name, class: "client-input" %>
                    </div>
                </div>
                <div class="add-client-form">
                    <div>
                        <%= f.label :phone_no, "Phone Number", class: "client-label"%>
                        <%= f.text_field :phone_no, class: "client-input"%>
                    </div>
                </div>
            </div> 
            <div class="left-section">
                
                <%= f.fields_for :short_loans do |loan_form| %>
                    <div class="errors">
                        <%= loan_form.object.errors.full_messages.join(", ") if loan_form.object.errors.any? %>
                    </div>
                    <%= loan_form.hidden_field :relationship_officer_id , value: current_user.id%>
                    <div class="add-client-form">
                        <div>
                            <%= loan_form.label :loan_amount, "Loan Amount", class: "client-label"%>
                            <i class="fa fa-calendar"></i>
                            <%= loan_form.text_field :loan_amount, class: "client-input"%>
                        </div>
                    </div>

                    <div class="add-client-form">
                        <div>
                            <%= loan_form.label :instalment_amount, "Instalment Amount", class: "client-label"%>
                            <%= loan_form.text_field :instalment_amount, class: "client-input" %>
                        </div>
                    </div>
                    <div class="add-client-form">
                        <div>
                            <%= loan_form.label :loan_duration, "Loan Duration", class: "client-label"%>
                            <%= loan_form.select :loan_duration, [5,7,10] %> 
                        </div>
                    </div>
                    <div class="add-client-form">
                        <div>
                            <%= loan_form.label :due_date, "Due Date", class: "client-label"%>
                            <i class="fa fa-calendar"></i>
                            <%= loan_form.text_field :due_date,class: "date client-input"%>
                            
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
                <%= f.submit "Save", class: "client-btn btn" %> 
            <% end %>
        
    </div>
</div>

app/views/clients/payment.js.erb
document.querySelector('#myModal').style.display = "block";

document.querySelector('.close-modal').onclick = function () {
    document.querySelector('#myModal').style.display = "none";
}

document.querySelector('.modal-btn').onclick = function () {
    document.querySelector('#myModal').style.display = "none";
}

app/views/clients/show.html.erb
<section class="show-client container" id="viewclient">
    <aside class="client-aside">
        <div>
            <p id="client-name"><%= @client.name %></p>
            <small id="phone-no">Phone No: <%= @client.phone_no%></small>
        </div>
        <div class="aside-info-hub">
            <div class="information-btn" id="p-info">
                <div class="icon">
                    <i class="fa fa-user"></i>
                </div>
                <div>
                    <p>Personal Information</p>
                </div>
            </div>
            <div class="information-btn" id="l-info">
                <div class="icon">
                    <i class="fa fa-money"></i>
                </div>
                <div>
                    <p>Loan Information</p>
                </div>
            </div>
        </div>
    </aside>
    <section id="client-info" class="client-information container">
        <div id="client-display">
            <%= render 'shared/client_personal_info', client: @client%>
        </div>
        <div id="loan-display">
            <%= render 'shared/loan_info', locals: {short_loan: @short_loan, client: @client } %>
        </div> 
        
    </section>

</section>

app/views/clients/update.js.erb
alert('updated')

document.getElementById('client-name').innerHTML = '<%= @client.name %>' ;
document.getElementById('phone-no').innerHTML = 'Phone No: <%= @client.phone_no %>';